name: ShopEasy CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t shopeasy-web ./docker

      - name: Run container
        run: docker run -d --name test -p 8080:80 shopeasy-web

      - name: Test website
        run: |
          sleep 3
          curl -f http://localhost:8080 || exit 1

      - name: Stop container
        run: docker stop test
